# Generated by Django 6.0.3 on 2026-04-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=500)),
                ('upload_blob_url', models.URLField(max_length=2000)),
                ('download_blob_url', models.URLField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_processing_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('DONE', 'Done')], default='UPLOADED', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
