# Generated by Django 6.0.3 on 2026-04-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_blur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='download_blob_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
