# Generated by Django 6.0.3 on 2026-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_blur', '0002_alter_filemetadata_download_blob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='file_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('WHITELIST_UPLOADED', 'Whitelist Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
